//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act_SetChargeDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> M0 { get; set; }
        public Nullable<decimal> M500 { get; set; }
        public Nullable<decimal> M1000 { get; set; }
        public Nullable<decimal> M3000 { get; set; }
        public Nullable<decimal> M5000 { get; set; }
        public Nullable<decimal> M10000 { get; set; }
        public Nullable<decimal> M20000 { get; set; }
        public Nullable<decimal> M30000 { get; set; }
        public Nullable<decimal> M50000 { get; set; }
    }
}
