//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act_ActiveRecord
    {
        public int Id { get; set; }
        public string SsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ActiveType { get; set; }
        public string ActiveName { get; set; }
        public Nullable<decimal> Bet { get; set; }
        public Nullable<decimal> InMoney { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public string CheckIp { get; set; }
        public string CheckMachine { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public string Remark { get; set; }
    }
}
