//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act_Day15FHSet
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GroupName { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> MinMoney { get; set; }
        public Nullable<decimal> MaxMoney { get; set; }
        public Nullable<int> HyNum { get; set; }
        public Nullable<decimal> Group3 { get; set; }
        public Nullable<int> IsUsed { get; set; }
        public Nullable<int> soft { get; set; }
    }
}
