//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_Bet
    {
        public int Id { get; set; }
        public Nullable<int> BetId { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public string aaa { get; set; }
        public string bbb { get; set; }
    }
}
