//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_ContractOper
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Bet { get; set; }
        public Nullable<decimal> Loss { get; set; }
        public Nullable<decimal> Per { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Allowed { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
    }
}
