//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_UserMoneyStatAll
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<decimal> GetCash { get; set; }
        public Nullable<decimal> Bet { get; set; }
        public Nullable<decimal> Win { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> Cancellation { get; set; }
        public Nullable<decimal> TranAccIn { get; set; }
        public Nullable<decimal> TranAccOut { get; set; }
        public Nullable<decimal> Give { get; set; }
        public Nullable<decimal> Change { get; set; }
        public Nullable<decimal> AgentFH { get; set; }
        public Nullable<decimal> Other { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Isflag { get; set; }
    }
}
