//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_UserBet
    {
        public int Id { get; set; }
        public string SsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> UserMoney { get; set; }
        public Nullable<int> LotteryId { get; set; }
        public Nullable<int> PlayId { get; set; }
        public string PlayCode { get; set; }
        public string IssueNum { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> SingleMoney { get; set; }
        public Nullable<decimal> Times { get; set; }
        public Nullable<int> Num { get; set; }
        public string Detail { get; set; }
        public Nullable<int> DX { get; set; }
        public Nullable<int> DS { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> PointMoney { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<int> WinNum { get; set; }
        public Nullable<decimal> WinBonus { get; set; }
        public Nullable<decimal> RealGet { get; set; }
        public string Pos { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<System.DateTime> STime2 { get; set; }
        public Nullable<int> IsOpen { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> IsDelay { get; set; }
        public Nullable<int> IsWin { get; set; }
        public Nullable<System.DateTime> STime9 { get; set; }
        public Nullable<bool> IsCheat { get; set; }
        public Nullable<int> ZhId { get; set; }
        public string Source { get; set; }
    }
}
