//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_UserEmail
    {
        public int ID { get; set; }
        public Nullable<int> SendId { get; set; }
        public Nullable<int> ReceiveId { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public int IsRead { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<int> IsDelSend { get; set; }
        public Nullable<int> IsDelReceive { get; set; }
    }
}
