//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_UserLevel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<decimal> DpPoint { get; set; }
        public Nullable<int> DpBonus { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
