//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_User
    {
        public int Id { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> UserGroup { get; set; }
        public Nullable<int> PointModel { get; set; }
        public Nullable<decimal> Point { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> Freezing { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> PayMethod { get; set; }
        public string PayBank { get; set; }
        public string PayAccount { get; set; }
        public string PayName { get; set; }
        public string PayPass { get; set; }
        public string PayBankAddress { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Dividends { get; set; }
        public Nullable<int> Quota { get; set; }
        public Nullable<int> ChildNum { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> LoginNum { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public Nullable<System.DateTime> OnTime { get; set; }
        public string IP { get; set; }
        public Nullable<int> IsOnline { get; set; }
        public Nullable<int> IsEnable { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<int> IsJoin { get; set; }
        public Nullable<int> IsDelay { get; set; }
        public Nullable<int> IsGetCash { get; set; }
        public Nullable<int> IsBet { get; set; }
        public Nullable<int> IsTranAcc { get; set; }
        public string EnableSeason { get; set; }
        public Nullable<System.DateTime> IsJoinTime { get; set; }
        public Nullable<System.DateTime> GetMoneyTime { get; set; }
        public Nullable<int> GetMoneyNum { get; set; }
        public Nullable<System.DateTime> STime8 { get; set; }
        public Nullable<System.DateTime> STime9 { get; set; }
        public Nullable<int> BLPoint { get; set; }
        public string Pic { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string UserCode { get; set; }
        public string TrueName { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<int> Source { get; set; }
        public string MerchantId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
    }
}
