//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_lotteryUrl
    {
        public int Id { get; set; }
        public Nullable<int> Lid { get; set; }
        public string LName { get; set; }
        public Nullable<int> typeId { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<int> IsUsed { get; set; }
    }
}
