//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Lottery
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> MinTimes { get; set; }
        public Nullable<decimal> MaxTimes { get; set; }
        public Nullable<int> IsOpen { get; set; }
        public Nullable<int> CloseTime { get; set; }
        public Nullable<int> second { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Ltype { get; set; }
        public Nullable<int> IsAuto { get; set; }
        public Nullable<int> IndexType { get; set; }
        public string Url { get; set; }
        public Nullable<int> AutoUrl { get; set; }
        public Nullable<int> IphoneIsOpen { get; set; }
        public Nullable<int> IphoneSort { get; set; }
        public string IphoneRemark { get; set; }
        public string IphoneImg { get; set; }
        public Nullable<int> IssNum { get; set; }
        public string ApiUrl { get; set; }
    }
}
