//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Admin
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> AtiveTime { get; set; }
        public Nullable<int> IsOnline { get; set; }
        public string SessionId { get; set; }
        public string Browser { get; set; }
        public string System { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> IsSuper { get; set; }
        public Nullable<decimal> MinCash { get; set; }
        public Nullable<decimal> MaxCash { get; set; }
    }
}
