//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PlaySmallType
    {
        public int Id { get; set; }
        public Nullable<int> LotteryId { get; set; }
        public Nullable<int> Radio { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title0 { get; set; }
        public string Title { get; set; }
        public string Title2 { get; set; }
        public string TitleName { get; set; }
        public string remark { get; set; }
        public string example { get; set; }
        public string help { get; set; }
        public Nullable<decimal> MaxBonus { get; set; }
        public Nullable<decimal> MinBonus { get; set; }
        public Nullable<decimal> PosBonus { get; set; }
        public Nullable<decimal> MaxBonus2 { get; set; }
        public Nullable<decimal> MinBonus2 { get; set; }
        public Nullable<decimal> PosBonus2 { get; set; }
        public Nullable<int> WzNum { get; set; }
        public Nullable<int> MinNum { get; set; }
        public Nullable<int> MaxNum { get; set; }
        public Nullable<int> Pos { get; set; }
        public Nullable<int> PosNum { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> randoms { get; set; }
        public Nullable<int> IsOpen { get; set; }
        public Nullable<int> IsOpenIphone { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
    }
}
