//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_LotteryData
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public string NumberAll { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> DX { get; set; }
        public Nullable<int> DS { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Flag2 { get; set; }
        public Nullable<int> IsFill { get; set; }
    }
}
