//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_TaskSet
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string StrSql { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> BeforeTime { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<int> IsUsed { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
