//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Info
    {
        public int Id { get; set; }
        public Nullable<int> WebIsOpen { get; set; }
        public string WebCloseSeason { get; set; }
        public Nullable<int> ZHIsOpen { get; set; }
        public Nullable<int> BetIsOpen { get; set; }
        public Nullable<int> RegIsOpen { get; set; }
        public string CSUrl { get; set; }
        public Nullable<int> SignMinTotal { get; set; }
        public Nullable<int> SignMaxTotal { get; set; }
        public Nullable<int> SignNum { get; set; }
        public Nullable<decimal> WarnTotal { get; set; }
        public Nullable<decimal> PointWarnTotal { get; set; }
        public Nullable<decimal> RealWarnTotal { get; set; }
        public Nullable<decimal> ActiveWarnTotal { get; set; }
        public Nullable<decimal> FhWarnTotal { get; set; }
        public Nullable<decimal> YLLWarnTotal { get; set; }
        public Nullable<decimal> GetCashWarnTotal { get; set; }
        public Nullable<decimal> MaxBet { get; set; }
        public Nullable<decimal> MaxWin { get; set; }
        public Nullable<decimal> MaxWinFK { get; set; }
        public Nullable<decimal> MaxLevel { get; set; }
        public Nullable<decimal> MinCharge { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<decimal> PriceOutCheck { get; set; }
        public Nullable<decimal> PriceOut { get; set; }
        public Nullable<decimal> PriceOut2 { get; set; }
        public Nullable<int> PriceNum { get; set; }
        public string PriceTime1 { get; set; }
        public string PriceTime2 { get; set; }
        public Nullable<decimal> BankTime { get; set; }
        public Nullable<int> PriceOutPerson { get; set; }
        public string ClientVersion { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> NewsUpdateTime { get; set; }
        public Nullable<int> AutoLottery { get; set; }
        public Nullable<int> ProfitModel { get; set; }
        public Nullable<int> ProfitMargin { get; set; }
        public Nullable<int> AutoRanking { get; set; }
        public Nullable<int> BetSQ { get; set; }
        public Nullable<decimal> BetSQMoney { get; set; }
    }
}
