//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ChargeSet
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public string MerName { get; set; }
        public string MerCode { get; set; }
        public string MerKey { get; set; }
        public string MerCard { get; set; }
        public Nullable<decimal> MinCharge { get; set; }
        public Nullable<decimal> MaxCharge { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IsUsed { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public string UCode { get; set; }
    }
}
