//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.FFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_BankBinInfo
    {
        public int Id { get; set; }
        public Nullable<int> BankId { get; set; }
        public string BankName { get; set; }
        public string BankInfo { get; set; }
        public string BankBin { get; set; }
        public Nullable<int> IsTrue { get; set; }
    }
}
