
var LotteryTypeJsonData = [
{ key: "0", value: "全部游戏" },
{ key: "1", value: "时时彩类" },
{ key: "2", value: "11选5类" },
{ key: "3", value: "3DP3类" },
{ key: "4", value: "北京PK10"}];

var LotteryJsonData = [
    { key: "", value: "全部游戏" },
    { key: "1001", value: "重庆时时彩" },
    { key: "1010", value: "韩国1.5分彩" },
    { key: "1017", value: "老韩国1.5分" },
    { key: "1015", value: "菲律宾1.5分" },
    { key: "1014", value: "老东京1.5分" },
    { key: "1016", value: "东京1.5分彩" },
    { key: "1012", value: "新加坡2分彩" },
    { key: "1013", value: "台湾5分彩" },
    { key: "1011", value: "新德里1.5分彩" },
    { key: "1018", value: "新加坡30秒彩" },
    { key: "1019", value: "台湾60秒彩" },
    { key: "1020", value: "首尔60秒彩" },
    { key: "1003", value: "新疆时时彩" },
    { key: "1004", value: "纽约30秒彩" },
    { key: "1005", value: "腾讯分分彩" },
    { key: "1009", value: "泰国一分彩" },
    { key: "1007", value: "天津时时彩" },
    { key: "1008", value: "云南时时彩" },
    { key: "2005", value: "一分11选5" },
    { key: "2001", value: "山东11选5" },
    { key: "2002", value: "广东11选5" },
    { key: "2003", value: "上海11选5" },
    { key: "2004", value: "江西11选5" },
    { key: "2006", value: "韩国11选5" },
    { key: "3001", value: "时时乐" },
    { key: "3002", value: "福彩3D" },
    { key: "3003", value: "体彩P3" },
    { key: "3004", value: "韩国3D" },
    { key: "3005", value: "首尔3D" },
    { key: "3006", value: "一分3d" },
    { key: "4001", value: "北京PK10" },
    { key: "4002", value: "一分PK10" },
    { key: "4003", value: "英国60秒赛车" },
    { key: "4004", value: "英国120秒赛车"}];

var Lottery2JsonData = [
    { key: "1001", value: "重庆时时彩" },
    { key: "1010", value: "韩国1.5分彩" },
    { key: "1017", value: "老韩国1.5分" },
    { key: "1015", value: "菲律宾1.5分" },
    { key: "1014", value: "老东京1.5分" },
    { key: "1016", value: "东京1.5分彩" },
    { key: "1012", value: "新加坡2分彩" },
    { key: "1013", value: "台湾5分彩" },
    { key: "1011", value: "新德里1.5分彩" },
    { key: "1018", value: "新加坡30秒彩" },
    { key: "1019", value: "台湾60秒彩" },
    { key: "1020", value: "首尔60秒彩" },
    { key: "1003", value: "新疆时时彩" },
    { key: "1004", value: "纽约30秒彩" },
    { key: "1005", value: "腾讯分分彩" },
    { key: "1009", value: "泰国一分彩" },
    { key: "1007", value: "天津时时彩" },
    { key: "1008", value: "云南时时彩" },
    { key: "2005", value: "一分11选5" },
    { key: "2001", value: "山东11选5" },
    { key: "2002", value: "广东11选5" },
    { key: "2003", value: "上海11选5" },
    { key: "2004", value: "江西11选5" },
    { key: "2006", value: "韩国11选5" },
    { key: "3001", value: "时时乐" },
    { key: "3002", value: "福彩3D" },
    { key: "3003", value: "体彩P3" },
    { key: "3004", value: "韩国3D" },
    { key: "3005", value: "首尔3D" },
    { key: "3006", value: "一分3d" },
    { key: "4001", value: "北京PK10" },
    { key: "4002", value: "一分PK10" },
    { key: "4003", value: "英国60秒赛车" },
    { key: "4004", value: "英国120秒赛车"}];

var MoneyStatOrderData = [
    { key: "", value: "默认排序" },
    { key: "Charge", value: "充值" },
    { key: "getcash", value: "提现" },
    { key: "bet", value: "投注" },
    { key: "win", value: "奖金" },
    { key: "Cancellation", value: "撤单" },
    { key: "Point", value: "返点" },
    { key: "Give", value: "活动" },
    { key: "other", value: "其他" },
    { key: "total", value: "报表盈亏" },
    { key: "moneytotal", value: "实际盈亏"}];

var HistoryJsonData = [
    { key: "", value: "所有类型" },
    { key: "1", value: "账号充值" },
    { key: "2", value: "账号提款" },
    { key: "3", value: "投注扣款" },
    { key: "4", value: "游戏返点" },
    { key: "5", value: "奖金派送" },
    { key: "6", value: "撤单返款" },
    { key: "7", value: "转出资金" },
    { key: "8", value: "转入资金" },
    { key: "9", value: "活动礼金" },
    { key: "10", value: "其他" },
    { key: "11", value: "积分兑换" },
    { key: "12", value: "分红"}];

var HistoryRepeatJsonData = [
    { key: "5", value: "奖金派送" },
    { key: "6", value: "撤单返款"}];

var ChargeJsonData = [
    { key: "", value: "所有类型" },
    { key: "1001", value: "充值线路1" },
    { key: "1002", value: "充值线路2" },
    { key: "1003", value: "充值线路3" },
    { key: "1004", value: "充值线路4" },
    { key: "1005", value: "微信支付1" },
    { key: "1006", value: "微信支付2" },
    { key: "1007", value: "支付宝" },
    { key: "888", value: "后台充值"}];

var ActiveJsonData = [
    { key: "", value: "所有类型" },
    { key: "ActGongZi4", value: "招商日结工资" },
    { key: "ActGongZi3", value: "特权直属工资" },
    { key: "ActGongZi2", value: "直属日结工资" },
    { key: "ActGongziContract", value: "契约工资" },
    { key: "ActYongJin", value: "亏损佣金" },
    { key: "RegCharge", value: "注册首充佣金" },
    { key: "Charge", value: "首充佣金" },
    { key: "ActBet", value: "消费大闯关"}];

var ActiveBFJsonData = [
    { key: "ActGongZi4", value: "招商日结工资" },
    { key: "ActGongZi3", value: "特权直属工资" },
    { key: "ActGongZi2", value: "直属日结工资" },
    { key: "ActGongziContract", value: "契约工资" },
    { key: "ActYongJin", value: "亏损佣金" },
    { key: "RegCharge", value: "注册首充佣金" },
    { key: "Charge", value: "首充佣金" },
    { key: "ActBet", value: "消费大闯关"}];

var AdminOperLog = [
    { key: "", value: "全部" },
    { key: "登录密码", value: "登录密码" },
    { key: "资金密码", value: "资金密码" },
    { key: "会员返点", value: "会员返点" },
    { key: "会员类型", value: "会员类型" },
    { key: "会员资金", value: "会员资金" },
    { key: "会员管理", value: "会员管理" },
    { key: "会员充值", value: "会员充值" },
    { key: "会员取款", value: "会员取款" },
    { key: "会员切线", value: "会员切线" },
    { key: "会员银行", value: "会员银行" },
    { key: "订单管理", value: "订单管理" },
    { key: "游戏管理", value: "游戏管理" },
    { key: "系统设置", value: "系统设置" },
    { key: "添加操作", value: "添加操作" },
    { key: "编辑操作", value: "编辑操作" },
    { key: "活动管理", value: "活动管理" },
    { key: "管理员管理", value: "管理员管理"}];

var AgentFHTypeJsonData = [
{ key: "", value: "全部" },
{ key: "3", value: "特权分红" },
{ key: "4", value: "招商分红" },
{ key: "99", value: "契约分红" }];
